name: course_dilaundry
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <4.0.0"

dependencies:
  d_button: ^0.0.10
#  d_info: ^0.2.0
  d_info: ^0.2.2
#  d_input: ^0.0.9
  d_input: ^0.0.9
#  d_method: ^0.2.0
  d_method: ^0.2.0
#  d_view: ^0.0.3
  d_view: ^0.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
#  flutter_riverpod: ^2.3.6
  flutter_riverpod: ^2.5.1
#  google_fonts: ^4.0.3
  google_fonts: ^4.0.3
#  http: ^0.13.5
  http: ^0.13.5
#  intl: ^0.18.1
  intl: ^0.18.1
#  shared_preferences: ^2.1.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  whatsapp_unilink: ^2.1.0
#  url_launcher: ^6.1.10
  url_launcher: ^6.2.6
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
